package com.farmrunautopilot.data.travel;

import lombok.Value;

@Value
public class RuneAmount
{
	int quantity;
	Rune rune;

	// Written out rather than generated by Lombok so it can be statically imported.
	public static RuneAmount of(int quantity, Rune rune)
	{
		return new RuneAmount(quantity, rune);
	}
}
